name: sadhana_cart
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  animated_text_kit: ^4.2.2
  animations: ^2.0.11
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.3
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  firebase_storage: ^12.4.2
  flutter_animate: ^4.5.2
  flutter_image_compress: ^2.4.0
  flutter_localization: ^0.3.2
  flutter_slidable: ^4.0.0
  flutter_staggered_animations: ^1.1.1
  fluttertoast: ^8.2.12
  glassmorphism: ^3.0.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  google_sign_in_web: ^0.12.4+3
  image_picker: ^1.1.2
  intl: ^0.20.2
  page_transition: ^2.2.1
  pedometer: ^4.0.0
  percent_indicator: ^4.2.3
  permission_handler: ^12.0.0+1
  provider: ^6.1.2
  razorpay_flutter: ^1.4.0
  rxdart: ^0.28.0
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  video_player: ^2.9.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# iOS-specific platform configuration
platforms:
  ios:
    pluginClass: none
