import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
import 'package:sadhana_cart/Customer/cart_model.dart';
import 'package:sadhana_cart/Customer/customer_splash_screen.dart';
import 'package:sadhana_cart/Customer/theme_provider.dart';
import 'package:sadhana_cart/Seller/Seller_Sign_In.dart';
import 'package:sadhana_cart/Seller/provider/get_sold_product_by_customer.dart';
import 'package:sadhana_cart/Seller/provider/seller_product_provider.dart';
import 'package:sadhana_cart/admin/admin_home_page.dart';
import 'package:sadhana_cart/admin/provider/admin_provider.dart';
import 'package:sadhana_cart/admin/provider/get_seller_application_provider.dart';
import 'package:sadhana_cart/admin/provider/product_provider.dart';
import 'firebase_options.dart'; // This file will be generated by `flutterfire configure`.

// void main() async {
//   WidgetsFlutterBinding.ensureInitialized();
//   await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform, // Add this line
//   );
//   // runApp(MyApp());
//   runApp(
//     ChangeNotifierProvider(
//       create: (context) => CartModel(),
//       child: MyApp(),
//     ),
//   );
//
// }
//
// class MyApp extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       debugShowCheckedModeBanner: false,
//       title: 'SadhnaCart Seller',
//       // theme: ThemeData(primarySwatch: Colors.blue),
//       theme: ThemeData(
//         // Define the color scheme with indigo as the primary color
//         colorScheme: ColorScheme.light(
//           primary: Colors.indigo.shade600, // Primary color (AppBar, buttons)
//           secondary: Colors.indigoAccent, // Secondary color (FAB, highlights)
//           surface: Colors.white, // Background for cards, dialogs
//           background: Colors.grey[100]!, // App background
//           onPrimary: Colors.white, // Text/icon color on primary
//           onSecondary: Colors.white, // Text/icon color on secondary
//           onSurface: Colors.black, // Text/icon color on surface
//           onBackground: Colors.black, // Text/icon color on background
//         ),
//
//         // Global TextField Theme
//         inputDecorationTheme: InputDecorationTheme(
//           enabledBorder: OutlineInputBorder(
//             borderRadius: BorderRadius.circular(8),
//             borderSide: BorderSide(
//               color: Colors.indigo.shade300, // Light indigo border
//               width: 1.0,
//             ),
//           ),
//           focusedBorder: OutlineInputBorder(
//             borderRadius: BorderRadius.circular(12),
//             borderSide: BorderSide(
//               color: Colors.indigo.shade700, // Darker indigo border
//               width: 1.5,
//             ),
//           ),
//           contentPadding: EdgeInsets.symmetric(vertical: 16, horizontal: 20),
//           filled: true,
//           fillColor: Colors.grey[50], // Light background for text fields
//         ),
//
//         // Button Theme
//         elevatedButtonTheme: ElevatedButtonThemeData(
//           style: ElevatedButton.styleFrom(
//             backgroundColor: Colors.indigo.shade700, // Button background color
//             foregroundColor: Colors.white, // Text color
//             shape: RoundedRectangleBorder(
//               borderRadius: BorderRadius.circular(10), // Button border radius
//             ),
//             padding: EdgeInsets.symmetric(vertical: 14, horizontal: 24),
//             textStyle: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
//           ),
//         ),
//
//         // Floating Action Button Theme
//         floatingActionButtonTheme: FloatingActionButtonThemeData(
//           backgroundColor: Colors.indigoAccent, // FAB background color
//           foregroundColor: Colors.white, // Icon color
//           shape: RoundedRectangleBorder(
//             borderRadius: BorderRadius.circular(16), // FAB border radius
//           ),
//         ),
//
//         // AppBar Theme
//         appBarTheme: AppBarTheme(
//           backgroundColor: Colors.indigo.shade700, // AppBar background color
//           foregroundColor: Colors.white, // Text and icon color
//           elevation: 4, // Shadow depth
//           centerTitle: true, // Center the title
//           titleTextStyle: TextStyle(
//             fontSize: 22,
//             fontWeight: FontWeight.bold,
//           ),
//           iconTheme: IconThemeData(color: Colors.white, size: 28),
//         ),
//
//         // Text Theme
//         textTheme: TextTheme(
//           displayLarge: TextStyle(fontSize: 32, fontWeight: FontWeight.bold, color: Colors.indigo.shade900),
//           displayMedium: TextStyle(fontSize: 28, fontWeight: FontWeight.bold, color: Colors.indigo.shade800),
//           bodyLarge: TextStyle(fontSize: 16, color: Colors.black),
//           bodyMedium: TextStyle(fontSize: 14, color: Colors.grey[800]),
//           labelLarge: TextStyle(fontSize: 16, fontWeight: FontWeight.bold, color: Colors.white),
//         ),
//       ),
//       home: SellerSignInScreen(),   //seller
//
//       home: AdminHomeScreen(),   // admin
//
//
//         home: SplashScreen(),   // customer
//     );
//   }
// }

// main

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => CartModel()),
        ChangeNotifierProvider(create: (_) => ThemeProvider()),
        ChangeNotifierProvider(create: (_) => GetSoldProductByCustomer()),
        ChangeNotifierProvider(create: (_) => GetSellerApplicationProvider()),
        ChangeNotifierProvider(create: (_) => ProductProvider()),
        ChangeNotifierProvider(create: (_) => AdminProvider()),
        ChangeNotifierProvider(create: (_) => SellerProductProvider()),
      ],
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    final themeProvider = Provider.of<ThemeProvider>(context);

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'SadhnaCart Seller',
      themeMode: themeProvider.themeMode,
      theme: ThemeData.light().copyWith(
          // your customized light theme code here...
          ),
      darkTheme: ThemeData.dark().copyWith(
        // Add dark theme customizations if needed
        primaryColor: Colors.grey[900],
        scaffoldBackgroundColor: Colors.grey[900],
        appBarTheme: AppBarTheme(
          backgroundColor: Colors.grey[850],
          foregroundColor: Colors.white,
        ),
        textTheme: const TextTheme(
          bodyLarge: TextStyle(color: Colors.white),
          bodyMedium: TextStyle(color: Colors.white70),
        ),
      ),

      // home: const AdminHomeScreen(),

      home: const SplashScreen(),

      // home: const SellerSignInScreen(), //seller

      // home: AdminHomeScreen(),   // admin
    );
  }
}




//







//basic pedometer 1 working

// import 'package:flutter/material.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'package:cloud_firestore/cloud_firestore.dart';
// import 'package:pedometer/pedometer.dart';
// import 'package:percent_indicator/circular_percent_indicator.dart';
// import 'package:animated_text_kit/animated_text_kit.dart';
// import 'package:permission_handler/permission_handler.dart';
//
// void main() async {
//   WidgetsFlutterBinding.ensureInitialized();
//   await Firebase.initializeApp();
//   runApp(FootstepApp());
// }
//
// class FootstepApp extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       title: 'Footstep Tracker',
//       theme: ThemeData.dark(useMaterial3: true).copyWith(
//         colorScheme: ColorScheme.dark(
//           primary: Colors.tealAccent,
//           secondary: Colors.teal,
//         ),
//       ),
//       debugShowCheckedModeBanner: false,
//       home: FootstepScreen(),
//     );
//   }
// }
//
// class FootstepScreen extends StatefulWidget {
//   @override
//   _FootstepScreenState createState() => _FootstepScreenState();
// }
//
// class _FootstepScreenState extends State<FootstepScreen> {
//   int _steps = 0;
//   int _dailyGoal = 5000;
//   String _status = 'Initializing...';
//   late Stream<StepCount> _stepCountStream;
//   late Stream<PedestrianStatus> _pedestrianStatusStream;
//
//   @override
//   void initState() {
//     super.initState();
//     _requestPermissions();
//   }
//
//   Future<void> _requestPermissions() async {
//     var status = await Permission.activityRecognition.request();
//     if (status.isGranted) {
//       initPlatformState();
//     } else {
//       setState(() {
//         _status = 'Permission denied';
//       });
//     }
//   }
//
//   void initPlatformState() {
//     _pedestrianStatusStream = Pedometer.pedestrianStatusStream;
//     _stepCountStream = Pedometer.stepCountStream;
//
//     _stepCountStream.listen((StepCount event) {
//       print("New steps: ${event.steps}");
//       _onStepCount(event);
//     }).onError((error) {
//       setState(() {
//         _status = 'Step Count Error: $error';
//       });
//     });
//
//     _pedestrianStatusStream.listen((PedestrianStatus event) {
//       print("Pedestrian status: ${event.status}");
//       _onPedestrianStatusChanged(event);
//     }).onError((error) {
//       print("Pedestrian Status error: $error");
//     });
//   }
//
//   void _onStepCount(StepCount event) {
//     setState(() {
//       _steps = event.steps;
//       _status = 'Counting steps...';
//     });
//     _saveStepsToFirestore();
//   }
//
//   void _onPedestrianStatusChanged(PedestrianStatus event) {
//     setState(() {
//       _status = event.status;
//     });
//   }
//
//   void _saveStepsToFirestore() async {
//     try {
//       final stepsRef = FirebaseFirestore.instance.collection('users').doc('demo_user');
//       await stepsRef.set({
//         'steps': _steps,
//         'timestamp': Timestamp.now(),
//       }, SetOptions(merge: true));
//     } catch (e) {
//       print("Firestore error: $e");
//     }
//   }
//
//   @override
//   Widget build(BuildContext context) {
//     double percent = (_steps / _dailyGoal).clamp(0, 1);
//
//     return Scaffold(
//       appBar: AppBar(
//         title: Text("🚶‍♂️ Step Tracker"),
//         centerTitle: true,
//         backgroundColor: Colors.transparent,
//         actions: [
//           IconButton(
//             icon: Icon(Icons.refresh),
//             onPressed: initPlatformState,
//             tooltip: 'Reinitialize pedometer',
//           )
//         ],
//       ),
//       body: Center(
//         child: Padding(
//           padding: const EdgeInsets.all(20.0),
//           child: Column(
//             children: [
//               AnimatedTextKit(
//                 animatedTexts: [
//                   WavyAnimatedText('Stay Active! 💪',
//                       textStyle: TextStyle(fontSize: 24, color: Colors.tealAccent)),
//                   WavyAnimatedText('Track Your Steps 🚶',
//                       textStyle: TextStyle(fontSize: 24, color: Colors.tealAccent)),
//                 ],
//                 repeatForever: true,
//               ),
//               const SizedBox(height: 20),
//               Text(
//                 _status,
//                 style: TextStyle(
//                   color: _status.contains('Error') || _status.contains('denied')
//                       ? Colors.red
//                       : Colors.tealAccent,
//                   fontSize: 16,
//                 ),
//               ),
//               const SizedBox(height: 20),
//               CircularPercentIndicator(
//                 radius: 120.0,
//                 lineWidth: 15.0,
//                 animation: true,
//                 percent: percent,
//                 center: Column(
//                   mainAxisAlignment: MainAxisAlignment.center,
//                   children: [
//                     Text(
//                       "$_steps",
//                       style: TextStyle(fontSize: 32, fontWeight: FontWeight.bold),
//                     ),
//                     Text(
//                       "Steps",
//                       style: TextStyle(fontSize: 16),
//                     ),
//                   ],
//                 ),
//                 circularStrokeCap: CircularStrokeCap.round,
//                 progressColor: Colors.tealAccent,
//                 backgroundColor: Colors.teal.withOpacity(0.2),
//               ),
//               const SizedBox(height: 40),
//               Text("Daily Goal: $_dailyGoal steps", style: TextStyle(fontSize: 16)),
//               Slider(
//                 value: _dailyGoal.toDouble(),
//                 min: 1000,
//                 max: 20000,
//                 divisions: 38,
//                 label: "$_dailyGoal",
//                 onChanged: (value) {
//                   setState(() {
//                     _dailyGoal = value.toInt();
//                   });
//                 },
//               ),
//               Spacer(),
//               ElevatedButton.icon(
//                 onPressed: () {
//                   setState(() {
//                     _steps = 0;
//                     _status = 'Counter reset';
//                   });
//                   _saveStepsToFirestore();
//                 },
//                 icon: Icon(Icons.refresh),
//                 label: Text("Reset Steps"),
//                 style: ElevatedButton.styleFrom(
//                   backgroundColor: Colors.tealAccent,
//                   foregroundColor: Colors.black,
//                   padding: EdgeInsets.symmetric(horizontal: 32, vertical: 12),
//                   shape: RoundedRectangleBorder(
//                       borderRadius: BorderRadius.circular(30)),
//                 ),
//               ),
//               SizedBox(height: 30),
//             ],
//           ),
//         ),
//       ),
//     );
//   }
// }


// enhansing pedometer


// import 'package:flutter/material.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'package:cloud_firestore/cloud_firestore.dart';
// import 'package:pedometer/pedometer.dart';
// import 'package:percent_indicator/circular_percent_indicator.dart';
// import 'package:animated_text_kit/animated_text_kit.dart';
// import 'package:permission_handler/permission_handler.dart';
// import 'package:sadhana_cart/main.dart';
//
//
// void main() async {
//   WidgetsFlutterBinding.ensureInitialized();
//   await Firebase.initializeApp();
//   runApp(FootstepApp());
// }






